# Generated by Django 3.0.5 on 2021-05-24 23:54

from django.db import migrations, models
import djongo.models.fields
import pedebem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('mesa', models.IntegerField()),
                ('items', djongo.models.fields.ArrayField(model_container=pedebem.models.Item)),
                ('atendente', djongo.models.fields.EmbeddedField(model_container=pedebem.models.Usuario)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=30)),
                ('descricao', models.TextField(max_length=256)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=30)),
                ('cpf', models.TextField(max_length=11)),
                ('role', models.CharField(choices=[('3', 'Caixa'), ('2', 'Atendente'), ('1', 'Cliente'), ('4', 'Gerente')], max_length=30)),
                ('login', models.TextField(max_length=30)),
                ('senha', models.TextField(max_length=30)),
            ],
        ),
    ]
