# Generated by Django 3.0.5 on 2021-05-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=30)),
                ('descricao', models.TextField(max_length=256)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=30)),
                ('cpf', models.TextField(max_length=11)),
                ('role', models.CharField(choices=[('4', 'Gerente'), ('2', 'Atendente'), ('3', 'Caixa'), ('1', 'Cliente')], max_length=30)),
                ('login', models.TextField(max_length=30)),
                ('senha', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField()),
                ('status', models.CharField(choices=[('2', 'Preparando'), ('1', 'Aguardando'), ('4', 'Entregue'), ('3', 'Pronto')], max_length=30)),
                ('atendente', models.ManyToManyField(to='pedebem.Usuario')),
                ('item', models.ManyToManyField(to='pedebem.Item')),
            ],
        ),
    ]
